[package]
description = "CosmWasm integration testing for Osmosis"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "osmosis-test-tube"
repository = "https://github.com/osmosis-labs/test-tube"
version = "25.0.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = ["osmosis", "test_artifacts"]

[dependencies]
base64 = "0.21.5"
cosmrs = { version = "0.23.0", features = ["cosmwasm"], git = "https://github.com/permissionlessweb/cosmos-rust" }
cosmwasm-std = "3.0.1"
osmosis-std = { version = "0.26.0", git = "https://github.com/permissionlessweb/osmosis-rust" }
prost = { version = "0.14.1", default-features = false }
serde = "1.0.144"
serde_json = "1.0.85"
test-tube = { version = "0.7.0", path = "../test-tube", features = [
    "module-wrappers",
] }
thiserror = "1.0.34"

[features]
default = []
wasm-sudo = ["test-tube/wasm-sudo"]

[build-dependencies]
bindgen = "0.69.1"

[dev-dependencies]
cw1-whitelist  = { git = "https://github.com/permissionlessweb/cw-plus",branch = "bump/v3", version = "3.0.0"  }
rayon = "1.5.3"
simple-sudo = { path = "../../test_contracts/simple-sudo" }
