[package]
description = "library for building integration testing environments for cosmos-sdk chains in Rust"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "test-tube"
repository = "https://github.com/osmosis-labs/test-tube"
version = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.5"
cosmrs = { version = "0.23.0", features = ["cosmwasm", "rpc"], git = "https://github.com/permissionlessweb/cosmos-rust" }
cosmwasm-std = { version = "3.0.1", features = ["stargate"] }
osmosis-std  = { version = "0.26.0", git = "https://github.com/permissionlessweb/osmosis-rust", optional = true }
prost = { version = "0.14.1", default-features = false }
serde = "1.0.144"
serde_json = "1.0.85"
thiserror = "1.0.34"

[dev-dependencies]
cw1-whitelist  = { git = "https://github.com/permissionlessweb/cw-plus",branch = "bump/v3", version = "3.0.0"  }
rayon = "1.5.3"

[features]
default = []
module-wrappers = ["bank", "wasm"]
wasm-sudo = []

bank = ["osmosis-std"]
wasm = ["osmosis-std"]
